config/routes.rb
Rails.application.routes.draw do

  resources :sales do
    member do
      get :ship_order
    end
  end

  resources :orders
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}

  resources :ads do
    member do
      get :toggle_published
    end
  end

  resources :charges

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'category_filter', to: 'ads#category_filter', as: 'ads_category_filter'
  get 'poster_filter', to: 'ads#poster_filter', as: 'ads_poster_filter'
  get 'purchase_ad', to: 'ads#purchase_ad', as: 'ads_purchase'
  get 'buy_ad', to: 'ads#buy_ad', as: 'ads_buy_ad'

  root to: 'ads#index'
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :category
  belongs_to :user
  after_initialize :set_defaults

  # Configure for Paperclip
  has_attached_file :photo, styles:
  {
    large: "600x600>",
    medium: "300x300>",
    thumb: "150x150#"
  }, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  validates_presence_of :title, :description, :price, :category_id, :quantity, :street, :city, :state, :zipcode
  validates :price,
            numericality: { :greater_than_or_equal_to => 0 }

  def set_defaults
    self.published ||= "draft"
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy, :toggle_published]
  before_action :set_categories, only: [:index, :category_filter, :poster_filter]
  before_action :set_users, only: [:poster_filter]
  before_action :authenticate_user!, only: [:poster_filter, :edit, :new, :create, :update, :buy_ad]
  before_action :set_current_user



  def index
    @ads = Ad.page(params[:page]).per(15).where(published: "published", sold: false).order(id: :desc)
    @page = __method__.to_s
  end

  def category_filter
    @ads = Ad.page(params[:page]).per(15).where(category_id: params[:category_id], published: "published", sold: false).order(id: :desc)
    @category = Category.find(params[:category_id])
    @page = __method__.to_s
  end

  # Filters by the ad's poster
  def poster_filter
    if params[:category_id] == nil
      @ads = Ad.page(params[:page]).per(15).where(user_id: params[:poster]).order(sold: :desc)
      @page = __method__.to_s
    else
      @ads = Ad.page(params[:page]).per(15).where(user_id: params[:poster], category_id: params[:category_id]).order(id: :desc)
      @page = __method__.to_s
    end
  end


  def buy_ad
    @ad = Ad.find(params[:ad_id])
    if current_user.id == @ad.user_id
      flash[:notice] = "You may not buy your own items."
      redirect_to ads_path
    else
      redirect_to new_order_path(:ad_id => @ad.id )
    end
  end


  def show
    @form_type = 'show'
    @page = __method__.to_s
  end


  def toggle_published
    if @ad.published == "published"
      @ad.update!(published: "draft")
      redirect_to ad_path, notice: "Your ad is now hidden."
    else
      @ad.update!(published: "published")
      redirect_to ads_url, notice: "Your ad has been posted!"
    end
  end


  def new
    @ad = Ad.new
    @form_type = 'new'
  end


  def edit
    @form_type = 'edit'
    @page = __method__.to_s
  end


  def create
    @ad = Ad.new(ad_params)
    @form_type = 'new'
    @ad.user = current_user

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @form_type = 'edit'
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end



  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: 'Ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    def set_categories
      @categories = Category.all
    end

    def set_users
      @users = User.all
    end

    def set_current_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:title, :description, :price, :category_id, :user_id, :photo, :quantity, :street, :city, :state, :zipcode)
    end

end

app/helpers/ads_helper.rb
module AdsHelper
  def show_ad_published_status(page, ad)
    if user_signed_in? && current_user.id == ad.user_id
      if page == "poster_filter"
        content_tag :div, :class => "ad-published-status" do
          content_tag :span, ad.published
        end
      end
    end
  end

  def display_published_toggle_btns(ad)
    if user_signed_in?
      if current_user.id == ad.user_id && ad.sold != true
        if ad.published == "draft"
          link_to "Post", toggle_published_ad_path(ad.id), class: "btn btn-success ad-action-btn float-right"
        else
          link_to "Hide", toggle_published_ad_path(ad.id), class: "btn btn-danger ad-action-btn float-right"
        end
      elsif current_user.id == ad.user_id && ad.sold == true
        link_to "Delete Ad", @ad, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger ad-action-btn float-right"
      end
    end
  end

  def display_edit_btns(ad)
    if user_signed_in?
      if current_user.id == ad.user_id && ad.sold != true
        form_button_helper(@form_type)
      end
    end
  end

  def allow_ad_edit(ad)
    if current_user.id != ad.user_id
      content_tag :div, :class => "no-content-container" do
        content_tag :h2, "You do not have permission to edit this ad."
      end
    else
      render 'form', ad: ad
    end
  end

  def show_purchase_container(ad)
    # Displays a Buy button that redirects users and non-users to different controller actions
    if user_signed_in?
      if current_user.id != ad.user_id
        ("<span class='ad-quantity-text'>Qty: #{ad.quantity}</span>").html_safe +
        (link_to "Buy", new_order_path(:ad_id => ad.id ), class: "btn btn-success buy-btn")
      end
    else
      ("<span class='ad-quantity-text'>Qty: #{ad.quantity}</span>").html_safe +
      (link_to "Buy", ads_buy_ad_url(:ad_id => ad.id), class: "btn btn-success buy-btn")
    end
  end

end

app/views/ads/_form.html.erb
<%= form_for @ad, :html => { :multipart => true } do |form| %>
  <% if ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ad.errors.count, "error") %> prohibited this ad from being saved:</h2>
      <ul>
      <% ad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-7">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, id: :ad_title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :price %>
        <%= form.text_field :price, id: :ad_price, class: "form-control" %>
      </div>

      <div class="form-group">
        <div class="form-group">
          <%= form.label :description %>
          <%= form.text_area :description, id: :ad_description, class: "form-control", rows: 20 %>
        </div>
      </div>
    </div>

    <div class="col-md-5">
      <div class="placeholder-form-photo">
        <%= image_tag @ad.photo %>
      </div>
      <div class="form-group">
        <%= form.label :photo %>
        <%= form.file_field :photo, id: :ad_photo, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :category_id %><br>
        <%= form.collection_select :category_id, Category.order(:name), :id, :name, include_blank: false %>
      </div>

      <div class="form-group quantity-select">
        <%= form.label :quantity %>
        <%= form.select :quantity, options_for_select([1,2,3,4,5,6,7,8,9,10], @ad.quantity), class: "form-control" %>
      </div>

      <div class="ad-address-container">
        <h5>Address</h5>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= form.label :street %>
              <%= form.text_field :street, id: :ad_street, class: "form-control" %>
            </div>
          </div>
          <div class="col-md-6">
            <%= form.label :city %>
            <%= form.text_field :city, id: :ad_city, class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <%= form.label :state %>
              <%= form.text_field :state, id: :ad_state, class: "form-control" %>
            </div>
          </div>
          <div class="col-md-6">
            <%= form.label :zipcode %>
            <%= form.text_field :zipcode, id: :zipcode, class: "form-control" %>
          </div>
        </div>
      </div>

    </div>
  </div>
  <br>

  <p style="float: right;"><%= form_button_helper(@form_type) %></p>
<% end %>

app/views/ads/_show_ad_content.html.erb
<% @ads.each do |ad| %>
    <div class="row ad-item">
      <div class="col-md-3">
        <div class="ad-photo-container">
          <%= link_to image_tag(ad.photo), ad, class: "img-fluid" %>
        </div>
      </div>
      <div class="col-md-9">
        <p class="ad-category-text"><%= ad.category.name %></p>
        <% if ad.sold %>
          <%= link_to ad.title, ad, class: "ad-title-text ad-sold-text" %>
          <br>
          <br>
          <p class="ad-sold-text">[ITEM SOLD - AD UNLISTED]</p>
        <% else %>
          <%= link_to ad.title, ad, class: "ad-title-text text-dark" %>
        <% end %>
        <p><%= ad.street %> <%= ad.city %>, <%= ad.state %> <%= ad.zipcode %></p>
        <p class="ad-price-text"><%= number_to_currency(ad.price) %></p>
        <p><%= simple_format(ad.description) %></p>
        <% if !ad.sold %>
          <%= show_ad_published_status(@page, ad) %>
        <% end %>
        <div class="ad-show-purchase-container">
          <%= show_purchase_container(ad) %>
        </div>
        <p class="ad-author-text">Posted By: <%= ad.user.first_name + " " + ad.user.last_name %></p>
      </div>
    </div>
<% end %>

app/views/ads/_show_filter_content.html.erb
<div class="filter-content">
  <button onclick="showFilterContainer()" class="btn btn-light btn-dark btn-block" id="show-filter-btn">Show Filters</button>
  <div id="filter-items-container">
    <% if @page != 'poster_filter' %>
      <%= link_to 'All', '#', class: "filter-item" %>
      <% @categories.each do |category| %>
        <%= link_to category.name, ads_category_filter_path(:category_id => category.id), class: "filter-item" %>
      <% end %>
    <% else %>
      <%= link_to 'All', ads_poster_filter_path(:poster => @user.id), class: "filter-item" %>
      <% @categories.each do |category| %>
        <%= link_to category.name, ads_poster_filter_path(:category_id => category.id, :poster => @user.id), class: "filter-item"  %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/ads/category_filter.html.erb
<div class="container-fluid">
  <div class="container ad-content-container">
    <h4 class="ad-main-header-text"><span class="capitalize"><%= @category.name %></span> Category</h4>
    <div class="row">
      <% if @ads.count != 0 %>
        <div class="col-lg-2">
          <%= render 'show_filter_content' %>
        </div>
        <div class="col-lg-10">
          <%= render 'show_ad_content' %>
        </div>
      <% else %>
        <div class="col-md-2">
          <%= render 'show_filter_content' %>
        </div>
        <div class="col-md-8">
          <div class="no-content-container bg-light">
            <h4>There are no ads in the <%= @category.name %> category.</h4>
            <%= link_to 'Return to main page', ads_path, class: "text-dark" %>
          </div>
        </div>
        <div class="col-md-2">

        </div>
      <% end %>
    </div>
    <div class="ad-pagination-container">
      <%= paginate @ads %>
    </div>
  </div>
</div>

app/views/ads/edit.html.erb
<div class="container-fluid">
  <div class="container ad-content-container">
    <h2>Edit Ad</h2>
    <%= allow_ad_edit(@ad) %>
  </div>
</div>

app/views/ads/index.html.erb
<div class="container-fluid">
  <div class="container ad-content-container">
    <h4 class="ad-main-header-text">All Published Ads</h4>
    <div class="row">
      <div class="col-lg-2">
        <%= render 'show_filter_content' %>
      </div>
      <div class="col-lg-10">
        <%= render 'show_ad_content' %>
      </div>
    </div>
    <div class="pagination-container">
      <%= paginate @ads %>
    </div>
  </div>
</div>

app/views/ads/new.html.erb
<div class="container-fluid">
  <div class="container ad-content-container">
    <h2>New Ad</h2>
    <%= render 'form', ad: @ad %>
  </div>
</div>

app/views/ads/poster_filter.html.erb
<div class="container-fluid">
  <div class="container poster-container">
    <h4 class="ad-main-header-text">Personal Ads</h4>  
    <div class="row">
      <!--  Handle when a user has no Ads -->
      <% if @ads.count == 0 %>
        <div class="col-lg-12">
          <div class="no-content-container">
            <h3>You have no listed ads</h3>
            <p>Want to create an ad? Click <%= link_to "here", new_ad_path %>.</p>
          </div>
        </div>
      <% else %>
        <div class="col-lg-2">
          <%= render 'show_filter_content' %>
        </div>
        <div class="col-lg-10">
          <%= render 'show_ad_content' %>
        </div>
      <% end %>
    </div>
    <div class="ad-pagination-container">
      <%= paginate @ads %>
    </div>
  </div>
</div>

app/views/ads/purchase_ad.html.erb
<div class="container-fluid">
  <div class="ad-purchase-container">
    <h1>Purchase Page</h1>
    <%= @ad.title %>
  </div>
</div>

app/views/ads/show.html.erb
<div class="container-fluid">
  <div class="container ad-content-container ad-show-container">
    <h2><%= @ad.title %></h2>
    <br>
    <p><%= @ad.street %> <%= @ad.city %>, <%= @ad.state %> <%= @ad.zipcode %></p>
    <br>
    <p>Quantity: <%= @ad.quantity %> (<%= number_to_currency(@ad.price) %> per item)</p>
    <br>
    <p><%= simple_format(@ad.description) %></p>
    <br>
    <div class="row ad-info-container">
      <div class="col-sm-4">
        <% if @ad.sold == false %>
          Visibility: <%= @ad.published.upcase %></span>
        <% end %>
      </div>
      <div class="col-sm-4">
        Posted by: <%= @ad.user.first_name + " " + @ad.user.last_name %>
      </div>
      <div class="col-sm-4">
        Category: <span class="capitalize"><%= @ad.category.name %></span>
      </div>
    </div>
    <br>
    <div class="ad-show-photo">
      <%= image_tag @ad.photo, class: "img-fluid" %>
    </div>
    <br>
    <%= display_edit_btns(@ad) %>
    <%= display_published_toggle_btns(@ad) %>
    <div class="ad-show-purchase-container">
      <%= show_purchase_container(@ad) %>
    </div>
  </div>
</div>