config/routes.rb
Rails.application.routes.draw do

  resources :sales do
    member do
      get :ship_order
    end
  end

  resources :orders
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}

  resources :ads do
    member do
      get :toggle_published
    end
  end

  resources :charges

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'category_filter', to: 'ads#category_filter', as: 'ads_category_filter'
  get 'poster_filter', to: 'ads#poster_filter', as: 'ads_poster_filter'
  get 'purchase_ad', to: 'ads#purchase_ad', as: 'ads_purchase'
  get 'buy_ad', to: 'ads#buy_ad', as: 'ads_buy_ad'

  root to: 'ads#index'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  validates_presence_of :address, :state, :zipcode, :city
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :new, :edit, :update, :destroy ]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @ad = Ad.find(params[:ad_id])

    @quantity_arr = []
    i = 1

    while i <= @ad.quantity do
      @quantity_arr.push(i)
      i += 1
    end
  end

  # GET /orders/1/edit
  def edit
    @ad = Ad.find(params[:ad_id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.buyer_last_name = params[:buyer_last_name]
    @order.buyer_first_name = params[:buyer_first_name]
    @ad = Ad.find(params[:ad_id])

    respond_to do |format|
      if @order.save
        format.html { redirect_to new_charge_path(:ad_id => @ad.id, :order_id => @order.id), notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    ad = Ad.find(params[:ad_id])
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to new_charge_path(:ad_id => ad.id, :order_id => @order.id), notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to '/', notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :state, :zipcode, :city, :user_id, :item_quantity, :buyer_last_name, :buyer_first_name)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h2 class="order-title-text">Purchase Page</h2>
  <br>
  <div class="row">
    <div class="col-md-4">
      <div class="card ad-preview-card" style="width: 18rem;">
        <%= image_tag @ad.photo, class: "card-img-top img-fluid" %>
        <div class="card-body">
          <h5 class="card-title"><%= @ad.title %></h5>
          <p class="card-text"><%= truncate(@ad.description, :length => 80) %></p>
        </div>
        <%= content_tag :span, "$" + @ad.price.to_s + " per item", class: "item-price-container mt-auto" %>
      </div>
    </div>
    <div class="col-md-8 order-address-container">
      <div class="form-group">
        <%= form.label :address %>
        <%= form.text_field :address, id: :order_address, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :state %>
        <%= form.text_field :state, id: :order_state, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :zipcode %>
        <%= form.number_field :zipcode, id: :order_zipcode, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :city %>
        <%= form.text_field :city, id: :order_city, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label "Quantity" %>
        <%= select_tag "order[item_quantity]", options_for_select(@quantity_arr, @ad.quantity) %>
      </div>
    </div>
  </div>

  <div class="actions order-btn-container">
    <%= link_to 'Back', '/', class: "btn btn-primary" %>
    <%= hidden_field_tag(:ad_id, @ad.id) %>
    <%= hidden_field_tag(:buyer_first_name, @user.first_name) %>
    <%= hidden_field_tag(:buyer_last_name, @user.last_name) %>
    <%= form.submit "Submit", class: "btn btn-success" %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<div class="container-fluid">
  <div class="container order-content-container">
    <h1>Editing Order</h1>

    <%= form_with(model: @order, local: true) do |form| %>
      <% if @order.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

          <ul>
          <% @order.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= form.label :address %>
        <%= form.text_field :address, id: :order_address, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :state %>
        <%= form.text_field :state, id: :order_state, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :zipcode %>
        <%= form.number_field :zipcode, id: :order_zipcode, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :city %>
        <%= form.text_field :city, id: :order_city, class: "form-control" %>
      </div>

      <%= hidden_field_tag(:ad_id, @ad.id) %>
      <%= form.submit "Submit", class: "btn btn-success" %>
    <% end %>

  </div>
</div>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Buyer name</th>
      <th>Seller name</th>
      <th>Payment confirmed</th>
      <th>Address</th>
      <th>State</th>
      <th>Zipcode</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.buyer_name %></td>
        <td><%= order.seller_name %></td>
        <td><%= order.payment_confirmed %></td>
        <td><%= order.address %></td>
        <td><%= order.state %></td>
        <td><%= order.zipcode %></td>
        <td><%= order.city %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<div class="container-fluid">
  <div class="container order-content-container">
    <%= render 'form', order: @order %>
  </div>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>State:</strong>
  <%= @order.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @order.zipcode %>
</p>

<p>
  <strong>City:</strong>
  <%= @order.city %>
</p>

<%= link_to 'Back', '/' %>