config/routes.rb
Rails.application.routes.draw do

  resources :sales do
    member do
      get :ship_order
    end
  end

  resources :orders
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}

  resources :ads do
    member do
      get :toggle_published
    end
  end

  resources :charges

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'category_filter', to: 'ads#category_filter', as: 'ads_category_filter'
  get 'poster_filter', to: 'ads#poster_filter', as: 'ads_poster_filter'
  get 'purchase_ad', to: 'ads#purchase_ad', as: 'ads_purchase'
  get 'buy_ad', to: 'ads#buy_ad', as: 'ads_buy_ad'

  root to: 'ads#index'
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:edit, :ship_order, :update, :destroy]
  before_action :set_user, only: [:new, :index, :ship_order]
  before_action :authenticate_user!

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.page(params[:page]).per(6).where(user_id: params[:user_id]).order(id: :desc)

    if current_user.id != params[:user_id].to_i
      flash[:notice] = "You do not have access to this page."
      redirect_to ads_url
    end
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  def ship_order
    # Production
    # @sale.update!(shipped: true)
    # flash[:notice] = "Your sale is now marked as shipped!"
    # redirect_to sales_url

    # Development method
    if @sale.shipped
      flash[:notice] = "SHIPPED TOGGLED"
      @sale.update!(shipped: false)
      redirect_to sales_url(:user_id => @user.id)
    else
      flash[:notice] = "Your sale is now marked as shipped!"
      @sale.update!(shipped: true)
      PurchaseMailer.shipped_order(@sale).deliver_now
      redirect_to sales_url(:user_id => @user.id)
    end
    # end development method
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.fetch(:sale, {})
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_with(model: sale, local: true) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sales/_show_sale_content.html.erb
<% @sales.each do |sale| %>
  <div class="col-md-4">
    <% if sale.shipped %>
      <div class="shipped-sale-card">
    <% else %>
      <div class="card sale-card">
    <% end %>
        <div class="card-body">
          <h5 class="card-title text-dark sale-card-title"><%= sale.ad_title %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= sale.created_at.strftime("%B %d, %Y") %> at <%= sale.created_at.strftime("%r")%></h6>
          <hr>
          <br>
          <p class="sale-card-subtitle">Address</p>
          <p class="card-text"><%= sale.shipping_street %> <%= sale.shipping_city %></p>
          <p class="card-text"><%= sale.shipping_state %> <%= sale.shipping_zipcode %></p>
          <hr>
          <br>
          <p class="sale-card-subtitle">Buyer Information</p>
          <p class="card-text"><%= sale.buyer_first_name %> <%= sale.buyer_last_name %></p>
          <p class="card-text"><%= sale.buyer_email %></p>
          <br>
          <div class="sale-block-container">
            <span class="sale-card-block">
              Quantity
              <hr>
              <%= sale.item_quantity %>
            </span>
            <span class="sale-card-block">
              Price
              <hr>
              $<%= sale.price %>
            </span>
            <span class="sale-card-block">
              Total
              <hr>
              $<%= sale.total_amount %>
            </span>
          </div>
          <br>
          <% if sale.shipped %>
              <p class="shipped-btn">Shipped</p>
          <% else %>
            <%= link_to "Ship Order", ship_order_sale_path(sale.id), class: "btn btn-block btn-info" %>
          <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<div class="container-fluid">
  <div class="container sale-content-container">
    <h4 class="sale-main-header-text">Sale Log</h4>
    <div class="row">
      <% if @sales.count != 0 %>
        <%= render 'show_sale_content' %>
      <% else %>
      <div class="no-content-container bg-light">
        <h4>You have no sale items.</h4>
        <%= link_to 'Return to home page', ads_path, class: "text-dark" %>
      </div>
      <% end %>
    </div>
    <div class="pagination-container">
        <%= paginate @sales %>
    </div>    
  </div>
</div>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<div class="container-fluid">
  <div class="container sale-content-container">
    <% unless @sale.shipped %>
      <h4 class="sale-main-header-text"><%= @sale.ad_title %> Sale</h4>
    <% else %>
      <h4 class="sale-main-header-text shipped-title-text"><%= @sale.ad_title %> has shipped</h4>
    <% end %>
        <div class="card sale-card">
          <div class="card-body">
            <div class="row">
              <div class="col-md-6">
                <h6 class="card-title sale-card-title">Buyer Information</h6>
                <p class="card-text"><%= @sale.buyer_first_name %> <%= @sale.buyer_last_name %></p>
                <p class="card-text"><%= @sale.shipping_street %> <%= @sale.shipping_city %></p>
                <p class="card-text"><%= @sale.shipping_state %> <%= @sale.shipping_zipcode %></p>
              </div>
              <div class="col-md-6">
                <h6 class="card-title sale-card-title">Sale Information</h6>
                <p class="card-text">Order placed on <%= @sale.created_at.strftime("%B %d, %Y") %> at <%= @sale.created_at.strftime("%r")%></p>
                <div class="row sale-block-container">

                  <div class="col-md-4">
                      <span class="sale-show-card-block">
                        Quantity
                        <hr>
                        <%= @sale.item_quantity %>
                      </span>
                  </div>
                  <div class="col-md-4">
                      <span class="sale-show-card-block">
                        Price per Unit
                        <hr>
                        <%= @sale.price %>
                      </span>
                  </div>
                  <div class="col-md-4">
                      <span class="sale-show-card-block">
                        Total
                        <hr>
                        <%= @sale.total_amount %>
                      </span>
                  </div>

                </div>
              </div>
            </div>
            <br>
            <br>
            <% unless @sale.shipped %>
              <%= link_to "Ship Order", ship_order_sale_path(@sale.id), class: "btn btn-success float-right" %>
            <% else %>
              <%= link_to "Delete Sale", @sale, method: :delete, data: { confirm: "Are you sure you want to delete this sale?" }, class: "btn btn-danger float-right" %>
            <% end %>
          </div>
        </div>
        <br>
        <br>
  </div>
</div>