config/routes.rb
Rails.application.routes.draw do

  resources :sales do
    member do
      get :ship_order
    end
  end

  resources :orders
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}

  resources :ads do
    member do
      get :toggle_published
    end
  end

  resources :charges

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'category_filter', to: 'ads#category_filter', as: 'ads_category_filter'
  get 'poster_filter', to: 'ads#poster_filter', as: 'ads_poster_filter'
  get 'purchase_ad', to: 'ads#purchase_ad', as: 'ads_purchase'
  get 'buy_ad', to: 'ads#buy_ad', as: 'ads_buy_ad'

  root to: 'ads#index'
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_current_user, only: [:new, :create]
  before_action :set_ad, only: [:new, :create]
  before_action :set_order, only: [:new, :create]

  def new
  end

  def create
    # Amount in cents
    @amount = ((@ad.price.to_f * 100) * @order.item_quantity.to_f).to_i

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

    @ad.quantity -= @order.item_quantity
    if @ad.quantity <= 0
      @ad.sold = true
    end
    @ad.save

    @order.completed = true
    @order.cost = @amount
    @order.save

    generate_sale_data

    PurchaseMailer.new_purchase(@ad, @order).deliver_now

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  private
    def set_ad
      @ad = Ad.find(params[:ad_id])
    end

    def set_order
      @order = Order.find(params[:order_id])
    end

    def set_current_user
      @user = current_user
    end

    def generate_sale_data
      # Create Sale entry for the order
      sale_hash = {
        :buyer_first_name => @order.buyer_first_name,
        :buyer_last_name => @order.buyer_last_name,
        :ad_title => @ad.title,
        :total_amount => (@ad.price.to_f * @order.item_quantity.to_f),
        :item_quantity => @order.item_quantity,
        :shipping_street => @order.address,
        :shipping_city => @order.city,
        :shipping_state => @order.state,
        :shipping_zipcode => @order.zipcode,
        :user_id => @ad.user_id,
        :price => @ad.price,
        :buyer_email => @user.email

      }
      @sale = Sale.new(sale_hash)
      @sale.save
    end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<div class="container-fluid">
  <div class="container charge-content-container">
    <h1>Thank you for your purchase!</h1>
    <p>The ad's seller has been notified and will ship your items soon.</p>
  </div>
</div>

app/views/charges/new.html.erb
<div class="container-fluid">
  <div class="container charge-content-container">
    <h2 class="charges-title-text">Confirm Purchase Info</h2>
    <br>
    <div class="row">
      <div class="col-md-4">
        <div class="card ad-preview-card" style="width: 18rem;">
          <%= image_tag @ad.photo, class: "card-img-top img-fluid" %>
          <div class="card-body d-flex flex-column">
            <h5 class="card-title"><%= @ad.title %></h5>
            <p class="card-text"><%= truncate(@ad.description, :length => 80) %></p>
              <%= content_tag :span, "Item Quantity: " + @order.item_quantity.to_s, class: "item-quantity-container mt-auto" %>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card charges-card" style="width: 18rem;">
          <%= image_tag "delivery.png", class: "card-img-top img-fluid" %>
          <div class="card-body d-flex flex-column">
            <h5 class="card-title">Delivery Info</h5>
            <p class="card-text"><%= @order.address %><br><%= @order.city %> <%= @order.state %>, <%= @order.zipcode %></p>
            <%= link_to "Change Address", edit_order_path(:id => @order.id, :ad_id => @ad.id), class: "mt-auto btn btn-info" %>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card charges-card" style="width: 18rem;">
          <%= image_tag "cc.png", class: "card-img-top img-fluid" %>
          <div class="card-body d-flex flex-column">
            <h5 class="card-title">Payment</h5>
            <p class="card-text">
              <%= form_tag charges_path do %>
                <article class="charge-card-body">
                  <% if flash[:error].present? %>
                    <div id="error_explanation">
                      <p><%= flash[:error] %></p>
                    </div>
                  <% end %>
                  <label class="amount">
                    <span>Amount: <%= number_to_currency(@ad.price * @order.item_quantity) %></span>
                  </label>
                </article>
            </p>
            <div class="charge-btn-container">
              <%= hidden_field_tag(:ad_id, @ad.id) %>
              <%= hidden_field_tag(:order_id, @order.id) %>
              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button mt-auto" id="stripe-btn"
                      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                      data-description="Purchase <%= @ad.title %>"
                      data-amount="<%= ((@ad.price.to_f * 100) * @order.item_quantity.to_f).to_s %>"
                      data-locale="auto"></script>
            </div>
          <% end %>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-lg-12">
        <%= link_to "Cancel Purchase", @order, method: :delete, data: { confirm: "Are you sure want to cancel? Your order will be deleted." }, class: "btn btn-danger ad-action-btn" %>
      </div>
    </div>
  </div>
</div>